### ISSUE TITLE
Any yeoman/gulp/grunt/twig/jade project for Opencart?

### ISSUE THREAD

**Issue by arnisjuraga** [opencart-ce/opencart-ce#82]
Hi!

It looks the CE is quite ended, but maybe someone can help - 
does anyone have used some templating, workflow solution for Opencart themes?

**Comment by opencarthelp** [comment]
I'm not quite sure what you're looking for.  Those technologies are all very different things.

**Comment by arnisjuraga** [comment]
e.g. Twig template for Opencart?

**Comment by opencarthelp** [comment]
No.  Twig integration would be a more suitable request for the official OpenCart repo.  CE is only aimed at bug and security fixes.
