### ISSUE TITLE
OOP and duplicated functionality

### ISSUE THREAD

**Issue by ap-oc** [opencart-ce/opencart-ce#86]
Is there something that could be done architecture-wise? Fixing the core OC design issues and updating it alongside core?

**Comment by arnisjuraga** [comment]
In Opencart core project - don't think so.
@daniel is so `clever`, that he knows everything the best! 

Making any design changes in core (no matter oopecnart-ce or opencart) will quickly break compatibilty issues with search-replace in source code modification system.

So, if you7 want to change something - ocmod modifications and modules will be the first what will break.

I have used another repo, for my development. But that's completely different repo.
